---
title: "learning_type_study"
author: "Gian Zlupko"
date: "11/11/2021"
output: html_document
---

```{r Setup, include=FALSE}
library(tidyverse) 
library(haven) 
library(psych) 
library(ggridges) 
library(car)
setwd("/Users/gianzlupko/Desktop/5123 Linear Models/5123_Linear_Models/Online_Learning_Study")   
```

Import data and view fields
```{r Import-Data}
learning <- read_dta("online_assessment.dta") 
head(learning) 
```


```{r Data-Cleaning}

# rename columns

learn2 <- learning %>%
  rename(course_grade = falsexam) 

# create column that stores character string identifying course type: 
learn2
learn2 <- learn2 %>%
  mutate(format_type = 
           ifelse(format_ol == 1, "online", 
                  ifelse(format_blended == 1, "hybrid", 
                         ifelse(format_ol == 0 & format_blended == 0, 
                                "traditional", "NA")))) 


# store format type as factor: 
class(learn2$format_type) 
learn2$format_type <- as.factor(learn2$format_type) 
levels(learn2$format_type) 

```



A review of missing data
```{r Missing-Data}

# attrition by instructional mode: 
# note, Alpert et al. (2016) coded drop out data 
# 1 = students given permission at outset of semester but did not sign up
# 2 = students who did enroll that later dropped out
# 3 = students who completed the course 

attrition <- learn2 %>%
  group_by(enroll_count) %>%
  select(format_type, enroll_count) %>%
  table() %>%
  data.frame()

#write.csv(attrition, "attrition_by_condition.csv") 
online_attrition = (29 + 50)
online_attrition/172

# store new data with only those who completed the course 

completed_course <- learn2 %>%
  filter(enroll_count == 3) 

# check missigness of GPA (covariate): 
# for those that completed coourse, 48 GPA records missing total
gpa_missing <- completed_course %>%
  select(format_type, gpa) %>%
  group_by(format_type) %>%
  filter(is.na(gpa)) %>%
  count(format_type)

#write.csv(gpa_missing, "gpa_missing.csv") 

# check missingness of final grade (DV): 
# no missing grades; DV accounted for. 

completed_course %>%
  select(format_type, course_grade) %>%
  group_by(format_type)

  
  

```







```{r Data-Cleaning2}

# filter data set for only those that completed the course 
completed <- learning %>%
  filter(!falsexam == 0 & !is.na(gpa)) 


```


Univariate graphical plots 

```{r Univariate-Plots}

# boxplot 
ggplot(data = completed_course, 
       aes(format_type, course_grade, fill = format_type)) + 
  geom_boxplot() + coord_flip() + ylab(label = "Final Grade") + 
  xlab("Class Format")+ labs(fill = "Class Format") +
  scale_x_discrete(labels=c("Traditional", "Online", "Hybrid")) 


ggplot(data = completed_course, 
       aes(course_grade, fill = format_type)) + geom_histogram()

# final grades by group histogram 
ggplot(data = completed_course, aes(x = course_grade)) +
  geom_histogram(fill = "white", colour = "black") +
  facet_grid(format_type ~ .) + xlab("Final Grade") + 
  ylab("Count")


# GPA by group 
ggplot(data = completed_course, aes(x = gpa)) +
  geom_histogram(fill = "white", colour = "black") +
  facet_grid(format_type ~ .) + xlab("GPA") + 
  ylab("Count") + stat_bin(bins = 8) 

# GPA distributions by group 

ggplot(data = completed_course, aes(x = gpa, y = format_type)) + 
  geom_joy(scale = 0.9) + 
  theme_joy() + scale_y_discrete(labels=c("Hybrid", "Online", "Traditional")) + 
  theme(legend.position = "none") + xlab("Student GPA") + ylab("Group") 


# QQ plot of grades to test normality assumption:

lm1 <- lm(course_grade ~ format_type, data = completed_course)
qqPlot(lm1)


```


```{r Descriptive-Statistics}

# final grade & GPA descriptive stats by group 
grade_desc <- describeBy(completed_course$course_grade, 
                         completed_course$format_type, mat = TRUE) 
gpa_desc <- describeBy(completed_course$gpa, 
           completed_course$format_type, mat = TRUE) 

#write.csv(grade_desc, "grade_descriptives.csv") 
#write.csv(gpa_desc, "gpa_descriptives.csv") 

```





```


Test for covariate suitability 

Is GPA an appropriate covariate to be used in ANCOVA? 
```{r Covariate-Test}

cor(completed$gpa, completed$falsexam)

lm(falsexam ~ gpa, data = completed) %>%
  summary()

ggplot(data = completed, aes(x = gpa, y = falsexam)) + geom_point() 

# test commit 
```





